name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          node-version: 17
      - name: vuepress-deploy
        uses: robineco/vuepress-deploy@v2.1
        with:
          node-version: 17
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: robineco/robineco.github.io
          TARGET_BRANCH: main
          BUILD_SCRIPT: npm install && npm build
          BUILD_DIR: dist
